# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  admin_email:
    type: string
    description: |
      Administrator's email address where root@ emails will go.
  domains:
    type: string
    description: |
      Comma or space separated list of sender domain(s) to sign
      messages for (empty will sign messages for all domains).
  keytable:
    type: string
    description: Key table mapping.
  mode:
    type: string
    default: 'sv'
    description: |
      Selects operating modes. The string is a concatenation of
      characters that indicate which mode(s) of operation are
      desired. Valid modes are s (signer) and v (verifier). The
      default is sv

      See http://www.opendkim.org/opendkim.conf.5.html
  selector:
    type: string
    default: 'mail'
    description: |
      Selector to use when signing messages with DKIM.
  signingtable:
    type: string
    description: Signing table mapping.
  trusted_sources:
    type: string
    description: |
      Comma-separated list of networks or hosts considered `trusted`
      to DKIM sign messages (empty will sign for all).
