name: Integration tests

on:
  pull_request:

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      extra-arguments: '-x --log-format="%(asctime)s %(levelname)s %(message)s"'
      self-hosted-runner: true
      self-hosted-runner-label: "edge"
      juju-channel: 3/stable
      provider: 'lxd'
      pre-run-script: ./tests/integration/setup-integration-tests.sh
      tmate-debug: true
